import java.util.Properties

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.compose.compiler)
    // Generates serializers for the @Serializable Navigation 3 keys.
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.ksp)
    alias(libs.plugins.hilt)
    // Consumes the baseline profile generated by :benchmark into the release build.
    alias(libs.plugins.baselineprofile)
}

// Local, never-committed configuration (secrets, endpoint overrides).
val localProperties: Properties =
    Properties().apply {
        val file = rootProject.file("local.properties")
        if (file.exists()) {
            file.inputStream().use { load(it) }
        }
    }

// GRAPHQL_URL comes from the environment (release CI) or local.properties (never
// committed). The emulator-localhost default is only a fallback so the project still
// builds without either.
val graphqlUrl: String =
    System.getenv("GRAPHQL_URL")
        ?: localProperties.getProperty("GRAPHQL_URL")
        ?: "http://10.0.2.2:8080/graphql"

// App version is derived from the latest semantic-version git tag: v1.2.3 → versionName
// "1.2.3" / versionCode 1_002_003 (room for 999 minors and patches each). Commits after
// the tag get a describe suffix ("1.2.3-4-gabc1234"); tagless checkouts fall back to a
// pre-release default.
val gitDescribe: String =
    providers
        .exec {
            commandLine("git", "describe", "--tags", "--match", "v[0-9]*")
            isIgnoreExitValue = true
        }.standardOutput.asText
        .get()
        .trim()
val appVersionName: String = gitDescribe.removePrefix("v").ifEmpty { "0.1.0" }
val appVersionCode: Int =
    Regex("""^(\d+)\.(\d+)\.(\d+)""")
        .find(appVersionName)
        ?.destructured
        ?.let { (major, minor, patch) ->
            major.toInt() * 1_000_000 + minor.toInt() * 1_000 + patch.toInt()
        } ?: 1

// Release signing comes from CI env vars (release.yml decodes the keystore secret to a
// file and passes its path as SIGNING_KEYSTORE_PATH) or, locally, from the same keys in
// local.properties. Only a path is read here — writing the keystore at configuration
// time would break with the configuration cache, which skips this script on a cache
// hit. Without a keystore (a contributor without secrets) the release build stays
// unsigned but still assembles.
fun signingProperty(name: String): String? = System.getenv(name) ?: localProperties.getProperty(name)

val signingKeystore: File? =
    signingProperty("SIGNING_KEYSTORE_PATH")
        ?.let { rootProject.file(it) }
        ?.takeIf { it.exists() }

android {
    namespace = "com.baruckis.ainews"
    compileSdk = libs.versions.compileSdk.get().toInt()

    defaultConfig {
        applicationId = "com.baruckis.ainews"
        minSdk = libs.versions.minSdk.get().toInt()
        targetSdk = libs.versions.targetSdk.get().toInt()
        versionCode = appVersionCode
        versionName = appVersionName

        buildConfigField("String", "GRAPHQL_URL", "\"$graphqlUrl\"")
    }

    signingConfigs {
        if (signingKeystore != null) {
            create("release") {
                storeFile = signingKeystore
                storePassword = signingProperty("SIGNING_STORE_PASSWORD")
                keyAlias = signingProperty("SIGNING_KEY_ALIAS")
                keyPassword = signingProperty("SIGNING_KEY_PASSWORD")
            }
        }
    }

    buildTypes {
        release {
            // Signed only when a keystore is available (CI secrets or local.properties);
            // null keeps the unsigned-but-buildable fallback for contributors.
            signingConfig = signingConfigs.findByName("release")
            // R8 (full mode is the AGP default) with resource shrinking: dead code and
            // unused resources are stripped, code is optimized and obfuscated.
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro",
            )
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    buildFeatures {
        compose = true
        buildConfig = true
    }

    testOptions {
        unitTests {
            // Robolectric needs the merged resources/manifest to inflate Compose content
            // in the navigation integration tests.
            isIncludeAndroidResources = true
            all { test ->
                // Default runs VERIFY each screenshot against its committed reference and
                // fail on any difference. Pass -Precord to (re)generate the references.
                val roborazziMode = if (project.hasProperty("record")) "record" else "verify"
                test.systemProperty("roborazzi.test.$roborazziMode", "true")
            }
        }
    }
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
    }
}

composeCompiler {
    // Strong skipping (skippable composables even with unstable params, memoized lambdas)
    // is enabled by default on this compiler version; the compiler warns if it is also
    // requested explicitly, so it is not repeated here. The reports under
    // docs/compose-metrics/ confirm it is active.
    // Marks the pure-Kotlin :core:model classes (and java.time.Instant) as stable without
    // adding a Compose dependency to the domain module.
    stabilityConfigurationFiles.add(rootProject.layout.projectDirectory.file("config/compose/stability.conf"))
    // Opt-in (slows compilation): -PcomposeCompilerReports writes the stability/skippability
    // reports consumed into docs/compose-metrics/.
    if (project.hasProperty("composeCompilerReports")) {
        metricsDestination = layout.buildDirectory.dir("compose-compiler")
        reportsDestination = layout.buildDirectory.dir("compose-compiler")
    }
}

baselineProfile {
    // Profiles are regenerated on demand (./gradlew :app:generateBaselineProfile) — GMD
    // generation is far too slow to run on every release assembly.
    automaticGenerationDuringBuild = false
}

dependencies {
    implementation(project(":feature:news"))
    implementation(project(":core:designsystem"))
    implementation(project(":core:model"))
    implementation(project(":core:mvi"))

    implementation(libs.androidx.core.ktx)
    // Compat splash screen shown while the first frame is being drawn.
    implementation(libs.androidx.core.splashscreen)
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.lifecycle.runtime.compose)

    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.material3)
    // WindowSizeClass via currentWindowAdaptiveInfo() drives the two-pane scene strategy.
    implementation(libs.compose.material3.adaptive)
    implementation(libs.compose.ui.tooling.preview)
    debugImplementation(libs.compose.ui.tooling)

    // Navigation 3: the back stack is a plain observable list; keys are @Serializable.
    implementation(libs.androidx.navigation3.runtime)
    implementation(libs.androidx.navigation3.ui)
    implementation(libs.androidx.lifecycle.viewmodel.navigation3)
    implementation(libs.kotlinx.serialization.core)

    // "Read at source" opens the article URL in a Chrome Custom Tab.
    implementation(libs.androidx.browser)

    // App-wide Coil ImageLoader (explicit memory/disk caches) built in AiNewsApplication.
    implementation(libs.coil.compose)
    // Installs the committed baseline profile on API levels without Play-store delivery.
    implementation(libs.androidx.profileinstaller)
    // :benchmark produces baseline-prof.txt; this wires its generator output into :app.
    baselineProfile(project(":benchmark"))

    implementation(libs.hilt.android)
    implementation(libs.androidx.hilt.lifecycle.viewmodel.compose)
    ksp(libs.hilt.compiler)

    // Navigation integration tests (Robolectric + Hilt): the fake repository module needs
    // the network result types, which :feature:news keeps as an implementation detail.
    testImplementation(project(":core:network"))
    testImplementation(libs.junit4)
    testImplementation(libs.robolectric)
    testImplementation(platform(libs.compose.bom))
    testImplementation(libs.compose.ui.test.junit4)
    testImplementation(libs.hilt.android.testing)
    kspTest(libs.hilt.compiler)
    // Tablet-width screenshot tests of the adaptive two-pane layout.
    testImplementation(libs.roborazzi)
    testImplementation(libs.roborazzi.compose)
}
