import java.util.Properties

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.compose.compiler)
    // Generates serializers for the @Serializable Navigation 3 keys.
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.ksp)
    alias(libs.plugins.hilt)
    // Consumes the baseline profile generated by :benchmark into the release build.
    alias(libs.plugins.baselineprofile)
}

// GRAPHQL_URL is read from local.properties (never committed). The emulator-localhost
// default is only a fallback so the project still builds without a local.properties file.
val graphqlUrl: String =
    Properties().apply {
        val file = rootProject.file("local.properties")
        if (file.exists()) {
            file.inputStream().use { load(it) }
        }
    }.getProperty("GRAPHQL_URL") ?: "http://10.0.2.2:8080/graphql"

android {
    namespace = "com.baruckis.ainews"
    compileSdk = libs.versions.compileSdk.get().toInt()

    defaultConfig {
        applicationId = "com.baruckis.ainews"
        minSdk = libs.versions.minSdk.get().toInt()
        targetSdk = libs.versions.targetSdk.get().toInt()
        versionCode = 1
        versionName = "0.1.0"

        buildConfigField("String", "GRAPHQL_URL", "\"$graphqlUrl\"")
    }

    buildTypes {
        release {
            // R8 (full mode is the AGP default) with resource shrinking: dead code and
            // unused resources are stripped, code is optimized and obfuscated.
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro",
            )
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    buildFeatures {
        compose = true
        buildConfig = true
    }

    testOptions {
        unitTests {
            // Robolectric needs the merged resources/manifest to inflate Compose content
            // in the navigation integration tests.
            isIncludeAndroidResources = true
            all { test ->
                // Default runs VERIFY each screenshot against its committed reference and
                // fail on any difference. Pass -Precord to (re)generate the references.
                val roborazziMode = if (project.hasProperty("record")) "record" else "verify"
                test.systemProperty("roborazzi.test.$roborazziMode", "true")
            }
        }
    }
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
    }
}

composeCompiler {
    // Strong skipping (skippable composables even with unstable params, memoized lambdas)
    // is enabled by default on this compiler version; the compiler warns if it is also
    // requested explicitly, so it is not repeated here. The reports under
    // docs/compose-metrics/ confirm it is active.
    // Marks the pure-Kotlin :core:model classes (and java.time.Instant) as stable without
    // adding a Compose dependency to the domain module.
    stabilityConfigurationFiles.add(rootProject.layout.projectDirectory.file("config/compose/stability.conf"))
    // Opt-in (slows compilation): -PcomposeCompilerReports writes the stability/skippability
    // reports consumed into docs/compose-metrics/.
    if (project.hasProperty("composeCompilerReports")) {
        metricsDestination = layout.buildDirectory.dir("compose-compiler")
        reportsDestination = layout.buildDirectory.dir("compose-compiler")
    }
}

baselineProfile {
    // Profiles are regenerated on demand (./gradlew :app:generateBaselineProfile) — GMD
    // generation is far too slow to run on every release assembly.
    automaticGenerationDuringBuild = false
}

dependencies {
    implementation(project(":feature:news"))
    implementation(project(":core:designsystem"))
    implementation(project(":core:model"))
    implementation(project(":core:mvi"))

    implementation(libs.androidx.core.ktx)
    // Compat splash screen shown while the first frame is being drawn.
    implementation(libs.androidx.core.splashscreen)
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.lifecycle.runtime.compose)

    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.material3)
    // WindowSizeClass via currentWindowAdaptiveInfo() drives the two-pane scene strategy.
    implementation(libs.compose.material3.adaptive)
    implementation(libs.compose.ui.tooling.preview)
    debugImplementation(libs.compose.ui.tooling)

    // Navigation 3: the back stack is a plain observable list; keys are @Serializable.
    implementation(libs.androidx.navigation3.runtime)
    implementation(libs.androidx.navigation3.ui)
    implementation(libs.androidx.lifecycle.viewmodel.navigation3)
    implementation(libs.kotlinx.serialization.core)

    // "Read at source" opens the article URL in a Chrome Custom Tab.
    implementation(libs.androidx.browser)

    // App-wide Coil ImageLoader (explicit memory/disk caches) built in AiNewsApplication.
    implementation(libs.coil.compose)
    // Installs the committed baseline profile on API levels without Play-store delivery.
    implementation(libs.androidx.profileinstaller)
    // :benchmark produces baseline-prof.txt; this wires its generator output into :app.
    baselineProfile(project(":benchmark"))

    implementation(libs.hilt.android)
    implementation(libs.androidx.hilt.lifecycle.viewmodel.compose)
    ksp(libs.hilt.compiler)

    // Navigation integration tests (Robolectric + Hilt): the fake repository module needs
    // the network result types, which :feature:news keeps as an implementation detail.
    testImplementation(project(":core:network"))
    testImplementation(libs.junit4)
    testImplementation(libs.robolectric)
    testImplementation(platform(libs.compose.bom))
    testImplementation(libs.compose.ui.test.junit4)
    testImplementation(libs.hilt.android.testing)
    kspTest(libs.hilt.compiler)
    // Tablet-width screenshot tests of the adaptive two-pane layout.
    testImplementation(libs.roborazzi)
    testImplementation(libs.roborazzi.compose)
}
